### ISSUE TITLE
bug in:  8. Call peaks on each of the pooled pseudoreplicate tag directories.

### ISSUE THREAD

**Issue by xflicsu** [karmel/homer-idr#2]
Hello, I use homer-idr to do idr analysis with the step as the readme shown to me.
And I find that there is no directory named "pseudoreps/pooled-pseudoreps" in step 8.
So, is there any other commands to produce files in that directory?
Thanks!

**Comment by karmel** [comment]
Yes-- in the beginning of that step, you create the directory with the mkdir command:

```
cd ~/CD4TCell-IDR
mkdir -p peaks/pooled-pseudoreps
cd peaks/pooled-pseudoreps
```

Does that help?

**Comment by xflicsu** [comment]
Sorry for the misleading words!
I mean there is no input directory named "pseudoreps/pooled-pseudoreps" (but not "peaks/pooled-pseudoreps") in the below command.

###########################
for f in ~/CD4TCell-IDR/pseudoreps/pooled-pseudoreps/*
..............
###########################

And I checked step 5 and step 6. Only two directory, "pseudoreps/individual" and "pseudoreps/pooled", were created.
So, when and how to create directory named "pseudoreps/pooled-pseudoreps" to prepare for input of step 8?

**Comment by karmel** [comment]
Ah, sorry for misreading-- that's a typo in the instructions, and should be 

```
for f in ~/CD4TCell-IDR/pseudoreps/pooled/*
```

which was created in step 6. I will update the text-- thanks!
