### ISSUE TITLE
Problem when running run_idr.py idr in the final steps "Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection"

### ISSUE THREAD

**Issue by jonasungerback** [karmel/homer-idr#5]
Hi,

thanks for a great code. I am trying to implement it right now and due to great instructions the setup and the generation of the pseudopeaks were simple. However when I am about to test the final parts of my idr testing:

python3 /Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/run_idr.py idr -p replicates/\* -pr pseudopreps/\* -ppr pooled-pseudoreps/\* --pooled_peaks pooled-replicates/\* -o idr-output

it starts to run nicely but a few iterations into the process I encounter the following problem at the end of the message.

I do not know if I have missed to set something in R or if I have forgotten anything in general but I would very much appreciate if you could help me with the problem.

Thank you so much!

Jonas

"cd /Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/idrCode && Rscript batch-consistency-plot.r 0 /Users/Jonas/Desktop/idr-test/idr-output/plots/Pooled_pseudorep_comparison
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'NA-uri.sav', probable reason 'No such file or directory'
Execution halted
Traceback (most recent call last):
  File "/Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/run_idr.py", line 385, in <module>
    parser.idr(options)
  File "/Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/run_idr.py", line 267, in idr
    output_prefix='Pooled_pseudorep_comparison')
  File "/Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/idr_caller.py", line 112, in plot_comparisons
    subprocess.check_call(cmd, shell=True)
  File "//anaconda/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /Users/Jonas/Documents/Arbetet/Biotoolkits/homer/homer-idr/idr/idrCode && Rscript batch-consistency-plot.r 0 /Users/Jonas/Desktop/idr-test/idr-output/plots/Pooled_pseudorep_comparison ' returned non-zero exit status 1"

**Comment by jonasungerback** [comment]
I manage to solve it and the problem was me. I just didn't move all my peak files properly. Things work better if you actually put things where you intend to. Thanks for a great tool.

Jonas

**Comment by karmel** [comment]
:) Glad it worked.
